import asyncio
import os
import sys
from datetime import datetime, timedelta, timezone
from uuid import uuid4

from motor.motor_asyncio import AsyncIOMotorClient

sys.path.append(os.path.dirname(os.path.dirname(__file__)))

from app.core.config import settings

SEED_JOBS = [
    {
        "title": "Frontend Engineer",
        "company": "Apple",
        "location": "Hyderabad",
        "work_mode": "onsite",
        "type": "Full-time",
        "ctc": "₹25 LPA",
        "deadline_offset_days": 14,
        "eligible_degrees": ["B.Tech", "B.E."],
        "eligible_branches": ["CSE", "IT", "ECE"],
        "eligible_graduation_years": [2024, 2025],
        "min_cgpa": 8.0,
        "max_backlogs": 0,
        "rounds": ["Resume Screen", "Technical Round 1", "Technical Round 2", "HR"],
        "application_link": "https://careers.apple.com/student",
        "source": "company-careers",
        "is_verified": True,
        "skills_required": ["React", "JavaScript", "TypeScript", "HTML", "CSS"],
    },
    {
        "title": "Full Stack Engineer - Java and React",
        "company": "Apple",
        "location": "Hyderabad",
        "work_mode": "hybrid",
        "type": "Full-time",
        "ctc": "₹28 LPA",
        "deadline_offset_days": 10,
        "eligible_degrees": ["B.Tech", "B.E.", "M.Tech"],
        "eligible_branches": ["CSE", "IT", "ECE", "EEE"],
        "eligible_graduation_years": [2024, 2025],
        "min_cgpa": 7.5,
        "max_backlogs": 1,
        "rounds": ["OA", "Technical Round", "Manager Round", "HR"],
        "application_link": "https://careers.apple.com/student",
        "source": "company-careers",
        "is_verified": True,
        "skills_required": ["Java", "React", "JavaScript", "REST API", "SQL"],
    },
    {
        "title": "Web Development Engineer",
        "company": "Amazon",
        "location": "Bengaluru",
        "work_mode": "onsite",
        "type": "Full-time",
        "ctc": "₹32 LPA",
        "deadline_offset_days": 21,
        "eligible_degrees": ["B.Tech", "B.E.", "MCA"],
        "eligible_branches": ["CSE", "IT"],
        "eligible_graduation_years": [2025],
        "min_cgpa": 8.5,
        "max_backlogs": 0,
        "rounds": ["Resume Screen", "OA", "Technical 1", "Technical 2", "Bar Raiser"],
        "application_link": "https://amazon.jobs",
        "source": "company-careers",
        "is_verified": True,
        "skills_required": ["React", "JavaScript", "TypeScript", "CSS"],
    },
    {
        "title": "Software Engineer (Frontend)",
        "company": "Teikametrics",
        "location": "India",
        "work_mode": "remote",
        "type": "Full-time",
        "ctc": "₹15 LPA",
        "deadline_offset_days": 7,
        "eligible_degrees": ["B.Tech", "B.E.", "BCA", "MCA"],
        "eligible_branches": ["CSE", "IT", "ECE"],
        "eligible_graduation_years": [2024, 2025],
        "min_cgpa": 7.0,
        "max_backlogs": 2,
        "rounds": ["OA", "Technical", "HR"],
        "application_link": "https://careers.teikametrics.com",
        "source": "company-careers",
        "is_verified": True,
        "skills_required": ["React", "JavaScript", "TypeScript", "CSS"],
    },
    {
        "title": "Frontend Engineer (React)",
        "company": "Fam",
        "location": "Bengaluru",
        "work_mode": "onsite",
        "type": "Full-time",
        "ctc": "₹18 LPA",
        "deadline_offset_days": 12,
        "eligible_degrees": ["B.Tech", "B.E."],
        "eligible_branches": ["CSE", "IT"],
        "eligible_graduation_years": [2025],
        "min_cgpa": 7.5,
        "max_backlogs": 0,
        "rounds": ["Take-home Assignment", "Technical", "Founders Round"],
        "application_link": "https://famapp.in/careers",
        "source": "company-careers",
        "is_verified": True,
        "skills_required": ["React", "JavaScript", "HTML", "CSS"],
    },
    {
        "title": "Frontend Engineer",
        "company": "Gushwork",
        "location": "Bengaluru",
        "work_mode": "hybrid",
        "type": "Full-time",
        "ctc": "₹12 LPA",
        "deadline_offset_days": 30,
        "eligible_degrees": ["B.Tech", "B.E.", "B.Sc", "BCA"],
        "eligible_branches": ["CSE", "IT", "Other"],
        "eligible_graduation_years": [2024, 2025],
        "min_cgpa": 6.5,
        "max_backlogs": 2,
        "rounds": ["Resume Screen", "Technical", "HR"],
        "application_link": "https://gushwork.ai/careers",
        "source": "company-careers",
        "is_verified": True,
        "skills_required": ["React", "JavaScript", "TypeScript", "CSS"],
    },
    {
        "title": "Frontend Developer",
        "company": "Z1 Tech",
        "location": "Gurugram",
        "work_mode": "onsite",
        "type": "Full-time",
        "ctc": "₹10 LPA",
        "deadline_offset_days": 5,
        "eligible_degrees": ["B.Tech", "B.E.", "MCA"],
        "eligible_branches": ["CSE", "IT", "ECE"],
        "eligible_graduation_years": [2024],
        "min_cgpa": 6.0,
        "max_backlogs": 1,
        "rounds": ["Technical 1", "Technical 2", "HR"],
        "application_link": "https://z1tech.com/careers",
        "source": "company-careers",
        "is_verified": True,
        "skills_required": ["React", "JavaScript", "CSS", "REST API"],
    },
    {
        "title": "Frontend Engineer",
        "company": "Weekday",
        "location": "Bengaluru",
        "work_mode": "remote",
        "type": "Full-time",
        "ctc": "₹14 LPA",
        "deadline_offset_days": 18,
        "eligible_degrees": ["B.Tech", "B.E."],
        "eligible_branches": ["CSE", "IT"],
        "eligible_graduation_years": [2025],
        "min_cgpa": 7.0,
        "max_backlogs": 0,
        "rounds": ["Resume Screen", "Technical"],
        "application_link": "https://weekday.works/careers",
        "source": "company-careers",
        "is_verified": True,
        "skills_required": ["React", "JavaScript", "HTML", "CSS"],
    },
    {
        "title": "Senior Frontend Engineer",
        "company": "Vendavo",
        "location": "Bengaluru",
        "work_mode": "hybrid",
        "type": "Full-time",
        "ctc": "₹20 LPA",
        "deadline_offset_days": 25,
        "eligible_degrees": ["B.Tech", "B.E.", "M.Tech", "MCA"],
        "eligible_branches": ["CSE", "IT", "ECE"],
        "eligible_graduation_years": [2024],
        "min_cgpa": 7.0,
        "max_backlogs": 0,
        "rounds": ["OA", "Technical 1", "Technical 2", "Manager"],
        "application_link": "https://vendavo.com",
        "source": "company-careers",
        "is_verified": True,
        "skills_required": ["React", "JavaScript", "TypeScript", "CSS"],
    },
    {
        "title": "UI Engineer",
        "company": "SAFE Security",
        "location": "Bengaluru",
        "work_mode": "hybrid",
        "type": "Full-time",
        "ctc": "₹22 LPA",
        "deadline_offset_days": 40,
        "eligible_degrees": ["B.Tech", "B.E."],
        "eligible_branches": ["CSE", "IT"],
        "eligible_graduation_years": [2024, 2025],
        "min_cgpa": 7.5,
        "max_backlogs": 0,
        "rounds": ["OA", "Technical", "HR"],
        "application_link": "https://safe.security/careers",
        "source": "company-careers",
        "is_verified": True,
        "skills_required": ["React", "TypeScript", "HTML", "CSS"],
    },
    {
        "title": "Full Stack Engineer",
        "company": "AHEAD",
        "location": "Bengaluru",
        "work_mode": "onsite",
        "type": "Full-time",
        "ctc": "₹16 LPA",
        "deadline_offset_days": 15,
        "eligible_degrees": ["B.Tech", "B.E."],
        "eligible_branches": ["CSE", "IT", "ECE"],
        "eligible_graduation_years": [2024, 2025],
        "min_cgpa": 7.0,
        "max_backlogs": 1,
        "rounds": ["Resume Screen", "Technical", "HR"],
        "application_link": "https://ahead.com/careers",
        "source": "company-careers",
        "is_verified": True,
        "skills_required": ["React", "TypeScript", "Python", "FastAPI", "SQL"],
    },
    {
        "title": "Store Technology Engineer (Full Stack)",
        "company": "ShyftLabs",
        "location": "Noida",
        "work_mode": "hybrid",
        "type": "Full-time",
        "ctc": "₹14 LPA",
        "deadline_offset_days": 12,
        "eligible_degrees": ["B.Tech", "B.E.", "MCA"],
        "eligible_branches": ["CSE", "IT"],
        "eligible_graduation_years": [2025],
        "min_cgpa": 6.5,
        "max_backlogs": 2,
        "rounds": ["OA", "Technical", "HR"],
        "application_link": "https://shyftlabs.io",
        "source": "company-careers",
        "is_verified": True,
        "skills_required": ["React", "TypeScript", "Python", "FastAPI", "SQL"],
    },
    {
        "title": "Full Stack Engineer",
        "company": "Level AI",
        "location": "Noida",
        "work_mode": "onsite",
        "type": "Full-time",
        "ctc": "₹24 LPA",
        "deadline_offset_days": 8,
        "eligible_degrees": ["B.Tech", "B.E.", "M.Tech"],
        "eligible_branches": ["CSE", "IT", "ECE", "EEE"],
        "eligible_graduation_years": [2024, 2025],
        "min_cgpa": 8.0,
        "max_backlogs": 0,
        "rounds": ["OA", "Machine Coding", "Technical", "Founders"],
        "application_link": "https://thelevel.ai",
        "source": "company-careers",
        "is_verified": True,
        "skills_required": ["React", "JavaScript", "Python", "Django", "REST API"],
    },
    {
        "title": "Product Engineer - AI Agents",
        "company": "100ms",
        "location": "Bengaluru",
        "work_mode": "hybrid",
        "type": "Full-time",
        "ctc": "₹28 LPA",
        "deadline_offset_days": 14,
        "eligible_degrees": ["B.Tech", "B.E."],
        "eligible_branches": ["CSE", "IT"],
        "eligible_graduation_years": [2024, 2025],
        "min_cgpa": 8.0,
        "max_backlogs": 0,
        "rounds": ["Resume Screen", "Take-home", "Technical", "Founders"],
        "application_link": "https://100ms.live",
        "source": "company-careers",
        "is_verified": True,
        "skills_required": ["React", "Python", "FastAPI", "Docker", "REST API"],
    },
    {
        "title": "Software Engineer Intern - Merchant Services",
        "company": "GoTo Group",
        "location": "India",
        "work_mode": "remote",
        "type": "Internship",
        "stipend": "₹60,000/mo",
        "deadline_offset_days": 21,
        "eligible_degrees": ["B.Tech", "B.E.", "M.Tech", "MCA"],
        "eligible_branches": ["CSE", "IT", "ECE"],
        "eligible_graduation_years": [2026],
        "min_cgpa": 7.0,
        "max_backlogs": 1,
        "rounds": ["OA", "Technical", "HR"],
        "application_link": "https://goto.com/careers",
        "source": "company-careers",
        "is_verified": True,
        "skills_required": ["Java", "Python", "JavaScript", "SQL"],
    },
    {
        "title": "Engineering Intern - App Team",
        "company": "PIP Labs",
        "location": "India",
        "work_mode": "remote",
        "type": "Internship",
        "stipend": "₹45,000/mo",
        "deadline_offset_days": 10,
        "eligible_degrees": ["B.Tech", "B.E.", "BCA", "B.Sc"],
        "eligible_branches": ["CSE", "IT", "ECE"],
        "eligible_graduation_years": [2026, 2027],
        "min_cgpa": 6.5,
        "max_backlogs": 2,
        "rounds": ["Resume Screen", "Technical", "HR"],
        "application_link": "https://piplabs.com",
        "source": "company-careers",
        "is_verified": True,
        "skills_required": ["React", "TypeScript", "Node", "CSS"],
    },
    {
        "title": "Software Engineer Intern",
        "company": "AiDash",
        "location": "Bengaluru",
        "work_mode": "hybrid",
        "type": "Internship",
        "stipend": "₹50,000/mo",
        "deadline_offset_days": 15,
        "eligible_degrees": ["B.Tech", "B.E."],
        "eligible_branches": ["CSE", "IT"],
        "eligible_graduation_years": [2025, 2026],
        "min_cgpa": 7.5,
        "max_backlogs": 0,
        "rounds": ["OA", "Technical 1", "Technical 2", "HR"],
        "application_link": "https://aidash.com",
        "source": "company-careers",
        "is_verified": True,
        "skills_required": ["Python", "Java", "React", "TypeScript"],
    },
    {
        "title": "Senior Engineer",
        "company": "Brillio",
        "location": "Bengaluru",
        "work_mode": "onsite",
        "type": "Full-time",
        "ctc": "₹16 LPA",
        "deadline_offset_days": 30,
        "eligible_degrees": ["B.Tech", "B.E.", "MCA", "M.Tech"],
        "eligible_branches": ["CSE", "IT", "ECE"],
        "eligible_graduation_years": [2023, 2024],
        "min_cgpa": 6.5,
        "max_backlogs": 0,
        "rounds": ["Technical 1", "Technical 2", "Manager"],
        "application_link": "https://brillio.com",
        "source": "company-careers",
        "is_verified": True,
        "skills_required": ["React", "Python", "FastAPI", "Docker", "SQL"],
    },
    {
        "title": "Full Stack Software Engineer",
        "company": "Sonatype",
        "location": "India",
        "work_mode": "remote",
        "type": "Full-time",
        "ctc": "₹22 LPA",
        "deadline_offset_days": 14,
        "eligible_degrees": ["B.Tech", "B.E.", "MCA"],
        "eligible_branches": ["CSE", "IT"],
        "eligible_graduation_years": [2024, 2025],
        "min_cgpa": 7.5,
        "max_backlogs": 0,
        "rounds": ["OA", "Machine Coding", "Technical", "HR"],
        "application_link": "https://sonatype.com",
        "source": "company-careers",
        "is_verified": True,
        "skills_required": ["React", "Node", "Python", "SQL"],
    },
    {
        "title": "Full Stack Engineer",
        "company": "Skypoint",
        "location": "Bengaluru",
        "work_mode": "hybrid",
        "type": "Full-time",
        "ctc": "₹18 LPA",
        "deadline_offset_days": 10,
        "eligible_degrees": ["B.Tech", "B.E."],
        "eligible_branches": ["CSE", "IT"],
        "eligible_graduation_years": [2024, 2025],
        "min_cgpa": 7.0,
        "max_backlogs": 1,
        "rounds": ["Technical", "Manager", "HR"],
        "application_link": "https://skypoint.com",
        "source": "company-careers",
        "is_verified": True,
        "skills_required": ["React", "Python", "SQL", "AWS"],
    },
    {
        "title": "Python Developer Intern",
        "company": "AHEAD",
        "location": "Hyderabad",
        "work_mode": "onsite",
        "type": "Internship",
        "stipend": "₹35,000/mo",
        "deadline_offset_days": 25,
        "eligible_degrees": ["B.Tech", "B.E.", "BCA", "M.Sc"],
        "eligible_branches": ["CSE", "IT", "ECE"],
        "eligible_graduation_years": [2026],
        "min_cgpa": 6.0,
        "max_backlogs": 2,
        "rounds": ["Resume Screen", "OA", "Technical"],
        "application_link": "https://ahead.com/careers",
        "source": "company-careers",
        "is_verified": True,
        "skills_required": ["Python", "FastAPI", "SQL", "Git"],
    },
    {
        "title": "Backend Engineer",
        "company": "Teikametrics",
        "location": "India",
        "work_mode": "remote",
        "type": "Full-time",
        "ctc": "₹16 LPA",
        "deadline_offset_days": 14,
        "eligible_degrees": ["B.Tech", "B.E.", "MCA", "M.Tech"],
        "eligible_branches": ["CSE", "IT", "ECE"],
        "eligible_graduation_years": [2024, 2025],
        "min_cgpa": 7.0,
        "max_backlogs": 1,
        "rounds": ["OA", "Technical", "HR"],
        "application_link": "https://teikametrics.com/careers",
        "source": "company-careers",
        "is_verified": True,
        "skills_required": ["Python", "REST API", "SQL", "Docker"],
    },
    {
        "title": "React UI Engineer",
        "company": "Vendavo",
        "location": "Bengaluru",
        "work_mode": "hybrid",
        "type": "Full-time",
        "ctc": "₹18 LPA",
        "deadline_offset_days": 20,
        "eligible_degrees": ["B.Tech", "B.E.", "MCA"],
        "eligible_branches": ["CSE", "IT", "ECE"],
        "eligible_graduation_years": [2024, 2025],
        "min_cgpa": 7.0,
        "max_backlogs": 0,
        "rounds": ["OA", "Technical 1", "Technical 2"],
        "application_link": "https://vendavo.com/careers",
        "source": "company-careers",
        "is_verified": True,
        "skills_required": ["React", "JavaScript", "HTML", "CSS"],
    },
    {
        "title": "Machine Learning Intern",
        "company": "VisionTrail",
        "location": "Remote",
        "work_mode": "remote",
        "type": "Internship",
        "stipend": "₹40,000/mo",
        "deadline_offset_days": 35,
        "eligible_degrees": ["B.Tech", "B.E.", "M.Tech", "M.Sc"],
        "eligible_branches": ["CSE", "IT", "Other"],
        "eligible_graduation_years": [2025, 2026],
        "min_cgpa": 7.5,
        "max_backlogs": 0,
        "rounds": ["Resume Screen", "Take-home", "Technical"],
        "application_link": "",
        "source": "seed",
        "is_verified": False,
        "skills_required": ["Python", "Machine Learning", "SQL"],
    },
]


async def main():
    client = AsyncIOMotorClient(settings.mongo_uri)
    db = client[settings.mongo_db]
    await db.jobs.delete_many({})
    now = datetime.now(timezone.utc)
    docs = []

    for i, base in enumerate(SEED_JOBS):
        doc = base.copy()
        doc["_id"] = str(uuid4())
        doc["posted_at"] = (now - timedelta(days=i % 21, hours=(i * 3) % 24)).isoformat()
        
        offset_days = doc.pop("deadline_offset_days", 14)
        doc["deadline"] = (now + timedelta(days=offset_days)).isoformat()
        
        docs.append(doc)

    await db.jobs.insert_many(docs)
    print(f"Seeded {len(docs)} jobs with full campus eligibility data")
    client.close()


if __name__ == "__main__":
    asyncio.run(main())
